### ISSUE TITLE
android.view.InflateException: Binary XML file line #12: Error inflating class android.support.v7.widget.RecyclerView

### ISSUE THREAD

**Issue by ishikota** [ishikota/Cappuchino#2]
Next error occurred When I run Cappuchino test.
It seems that this error occurs when test target Activity using RecyclerView.

> android.view.InflateException: Binary XML file line #12: Error inflating class android.support.v7.widget.RecyclerView
> at android.view.LayoutInflater.createView(LayoutInflater.java:633)
> at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
> at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
> at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
> at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
> at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
> at jp.ikota.drive.ui.basicimagelist.BasicImageListFragment.onCreateView(BasicImageListFragment.java:69)
> at ...
> ... 31 more
> Suppressed: java.lang.ClassNotFoundException: Invalid name: android.support.v7.widget.@2131230980
> at java.lang.Class.classForName(Native Method)
> at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
> at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
> at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
> ... 33 more

**Comment by ishikota** [comment]
Try this code in your build.gradle file.

**before**

``` groovy
dependencies {
    androidTestCompile 'jp.ikota:cappuchino:0.0.1'
}
```

**after**

``` groovy
dependencies {
   androidTestCompile ('jp.ikota:cappuchino:0.0.1') {
    exclude module: 'recyclerview-v7'
   }
}
```
